apiVersion: v1
kind: Service
metadata:
  name: emulatorjs
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30081
    - name: app
      port: 3000
      targetPort: 3000
      nodePort: 30080
    - name: api
      port: 4001
      targetPort: 4001
      nodePort: 30082
  selector:
    app: emulatorjs
